// Code generated by entc, DO NOT EDIT.

package ent

import (
	"github.com/starryrbs/kfan/app/account/internal/data/ent/account"
	"github.com/starryrbs/kfan/app/account/internal/data/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	accountFields := schema.Account{}.Fields()
	_ = accountFields
	// accountDescName is the schema descriptor for name field.
	accountDescName := accountFields[1].Descriptor()
	// account.DefaultName holds the default value on creation for the name field.
	account.DefaultName = accountDescName.Default.(string)
	// accountDescAge is the schema descriptor for age field.
	accountDescAge := accountFields[2].Descriptor()
	// account.DefaultAge holds the default value on creation for the age field.
	account.DefaultAge = accountDescAge.Default.(int)
	// accountDescID is the schema descriptor for id field.
	accountDescID := accountFields[0].Descriptor()
	// account.IDValidator is a validator for the "id" field. It is called by the builders before save.
	account.IDValidator = accountDescID.Validators[0].(func(int) error)
}
