// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// protoc-gen-go-http v2.1.3

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

type HouseHTTPServer interface {
	CreateHouse(context.Context, *CreateHouseRequest) (*CreateHouseReply, error)
	GetHouse(context.Context, *GetHouseRequest) (*GetHouseReply, error)
	ListHouse(context.Context, *ListHouseRequest) (*ListHouseReply, error)
}

func RegisterHouseHTTPServer(s *http.Server, srv HouseHTTPServer) {
	r := s.Route("/")
	r.POST("/v1/houses", _House_CreateHouse0_HTTP_Handler(srv))
	r.GET("/v1/houses/{id}", _House_GetHouse0_HTTP_Handler(srv))
	r.GET("/v1/houses", _House_ListHouse0_HTTP_Handler(srv))
}

func _House_CreateHouse0_HTTP_Handler(srv HouseHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateHouseRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, "/api.house.service.v1.House/CreateHouse")
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateHouse(ctx, req.(*CreateHouseRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreateHouseReply)
		return ctx.Result(200, reply)
	}
}

func _House_GetHouse0_HTTP_Handler(srv HouseHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetHouseRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, "/api.house.service.v1.House/GetHouse")
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetHouse(ctx, req.(*GetHouseRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetHouseReply)
		return ctx.Result(200, reply)
	}
}

func _House_ListHouse0_HTTP_Handler(srv HouseHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListHouseRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, "/api.house.service.v1.House/ListHouse")
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListHouse(ctx, req.(*ListHouseRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListHouseReply)
		return ctx.Result(200, reply)
	}
}

type HouseHTTPClient interface {
	CreateHouse(ctx context.Context, req *CreateHouseRequest, opts ...http.CallOption) (rsp *CreateHouseReply, err error)
	GetHouse(ctx context.Context, req *GetHouseRequest, opts ...http.CallOption) (rsp *GetHouseReply, err error)
	ListHouse(ctx context.Context, req *ListHouseRequest, opts ...http.CallOption) (rsp *ListHouseReply, err error)
}

type HouseHTTPClientImpl struct {
	cc *http.Client
}

func NewHouseHTTPClient(client *http.Client) HouseHTTPClient {
	return &HouseHTTPClientImpl{client}
}

func (c *HouseHTTPClientImpl) CreateHouse(ctx context.Context, in *CreateHouseRequest, opts ...http.CallOption) (*CreateHouseReply, error) {
	var out CreateHouseReply
	pattern := "/v1/houses"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation("/api.house.service.v1.House/CreateHouse"))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *HouseHTTPClientImpl) GetHouse(ctx context.Context, in *GetHouseRequest, opts ...http.CallOption) (*GetHouseReply, error) {
	var out GetHouseReply
	pattern := "/v1/houses/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation("/api.house.service.v1.House/GetHouse"))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *HouseHTTPClientImpl) ListHouse(ctx context.Context, in *ListHouseRequest, opts ...http.CallOption) (*ListHouseReply, error) {
	var out ListHouseReply
	pattern := "/v1/houses"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation("/api.house.service.v1.House/ListHouse"))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}
