// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.17.3
// source: api/house/service/v1/house.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// HouseClient is the client API for House service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HouseClient interface {
	CreateHouse(ctx context.Context, in *CreateHouseRequest, opts ...grpc.CallOption) (*CreateHouseReply, error)
	GetHouse(ctx context.Context, in *GetHouseRequest, opts ...grpc.CallOption) (*GetHouseReply, error)
	ListHouse(ctx context.Context, in *ListHouseRequest, opts ...grpc.CallOption) (*ListHouseReply, error)
}

type houseClient struct {
	cc grpc.ClientConnInterface
}

func NewHouseClient(cc grpc.ClientConnInterface) HouseClient {
	return &houseClient{cc}
}

func (c *houseClient) CreateHouse(ctx context.Context, in *CreateHouseRequest, opts ...grpc.CallOption) (*CreateHouseReply, error) {
	out := new(CreateHouseReply)
	err := c.cc.Invoke(ctx, "/api.house.service.v1.House/CreateHouse", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *houseClient) GetHouse(ctx context.Context, in *GetHouseRequest, opts ...grpc.CallOption) (*GetHouseReply, error) {
	out := new(GetHouseReply)
	err := c.cc.Invoke(ctx, "/api.house.service.v1.House/GetHouse", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *houseClient) ListHouse(ctx context.Context, in *ListHouseRequest, opts ...grpc.CallOption) (*ListHouseReply, error) {
	out := new(ListHouseReply)
	err := c.cc.Invoke(ctx, "/api.house.service.v1.House/ListHouse", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HouseServer is the server API for House service.
// All implementations must embed UnimplementedHouseServer
// for forward compatibility
type HouseServer interface {
	CreateHouse(context.Context, *CreateHouseRequest) (*CreateHouseReply, error)
	GetHouse(context.Context, *GetHouseRequest) (*GetHouseReply, error)
	ListHouse(context.Context, *ListHouseRequest) (*ListHouseReply, error)
	mustEmbedUnimplementedHouseServer()
}

// UnimplementedHouseServer must be embedded to have forward compatible implementations.
type UnimplementedHouseServer struct {
}

func (UnimplementedHouseServer) CreateHouse(context.Context, *CreateHouseRequest) (*CreateHouseReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateHouse not implemented")
}
func (UnimplementedHouseServer) GetHouse(context.Context, *GetHouseRequest) (*GetHouseReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetHouse not implemented")
}
func (UnimplementedHouseServer) ListHouse(context.Context, *ListHouseRequest) (*ListHouseReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListHouse not implemented")
}
func (UnimplementedHouseServer) mustEmbedUnimplementedHouseServer() {}

// UnsafeHouseServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HouseServer will
// result in compilation errors.
type UnsafeHouseServer interface {
	mustEmbedUnimplementedHouseServer()
}

func RegisterHouseServer(s grpc.ServiceRegistrar, srv HouseServer) {
	s.RegisterService(&House_ServiceDesc, srv)
}

func _House_CreateHouse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateHouseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HouseServer).CreateHouse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.house.service.v1.House/CreateHouse",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HouseServer).CreateHouse(ctx, req.(*CreateHouseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _House_GetHouse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHouseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HouseServer).GetHouse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.house.service.v1.House/GetHouse",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HouseServer).GetHouse(ctx, req.(*GetHouseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _House_ListHouse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListHouseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HouseServer).ListHouse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.house.service.v1.House/ListHouse",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HouseServer).ListHouse(ctx, req.(*ListHouseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// House_ServiceDesc is the grpc.ServiceDesc for House service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var House_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.house.service.v1.House",
	HandlerType: (*HouseServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateHouse",
			Handler:    _House_CreateHouse_Handler,
		},
		{
			MethodName: "GetHouse",
			Handler:    _House_GetHouse_Handler,
		},
		{
			MethodName: "ListHouse",
			Handler:    _House_ListHouse_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/house/service/v1/house.proto",
}
