// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"github.com/starryrbs/kfan/app/history/service/internal/conf"
	"github.com/starryrbs/kfan/app/history/service/internal/data"
	"github.com/starryrbs/kfan/app/history/service/internal/job"
)

// Injectors from wire.go:

// initApp init kratos application.
func initApp(server *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	jobData, cleanup, err := data.NewJobData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	historyJobRepo := data.NewHistoryJobRepo(jobData, logger)
	consumerGroup, err := data.NewKafkaConsumeGroup(confData)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	saramaConsumerJobServer := job.NewJobServer(historyJobRepo, confData, consumerGroup)
	app := newApp(logger, saramaConsumerJobServer)
	return app, func() {
		cleanup()
	}, nil
}
