server:
  http:
    addr: 0.0.0.0:7000
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1s
data:
  database:
    driver: mysql
    source: root:@tcp(127.0.0.1:3306)/account?parseTime=true
  redis:
    addr: 127.0.0.1:6379
    read_timeout: 0.2s
    write_timeout: 0.2s

registry:
  consul:
    address: 127.0.0.1:8500
    scheme: http