// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"github.com/starryrbs/kfan/app/account/internal/biz"
	"github.com/starryrbs/kfan/app/account/internal/conf"
	"github.com/starryrbs/kfan/app/account/internal/data"
	"github.com/starryrbs/kfan/app/account/internal/server"
	"github.com/starryrbs/kfan/app/account/internal/service"
)

// Injectors from wire.go:

// initApp init kratos application.
func initApp(confServer *conf.Server, confData *conf.Data, registry *conf.Registry, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	accountRepo := data.NewAccountRepo(dataData, logger)
	accountUseCase := biz.NewAccountUseCase(accountRepo, logger)
	accountInterface := service.NewAccountInterface(accountUseCase, logger)
	httpServer := server.NewHTTPServer(confServer, accountInterface, logger)
	grpcServer := server.NewGRPCServer(confServer, accountInterface, logger)
	registrar := data.NewRegistrar(registry)
	app := newApp(logger, httpServer, grpcServer, registrar)
	return app, func() {
		cleanup()
	}, nil
}
