// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"github.com/starryrbs/kfan/app/history/service/internal/biz"
	"github.com/starryrbs/kfan/app/history/service/internal/conf"
	"github.com/starryrbs/kfan/app/history/service/internal/data"
	"github.com/starryrbs/kfan/app/history/service/internal/server"
	"github.com/starryrbs/kfan/app/history/service/internal/service"
)

// Injectors from wire.go:

// initApp init kratos application.
func initApp(confServer *conf.Server, confData *conf.Data, registry *conf.Registry, logger log.Logger) (*kratos.App, func(), error) {
	asyncProducer := data.NewKafkaProducer(confData)
	discovery := data.NewDiscovery(registry)
	houseClient := data.NewHouseClient(discovery)
	accountClient := data.NewAccountClient(discovery)
	dataData, cleanup, err := data.NewData(asyncProducer, confData, houseClient, accountClient, logger)
	if err != nil {
		return nil, nil, err
	}
	historyRepo := data.NewHistoryRepo(dataData, logger)
	historyUseCase := biz.NewHistoryUseCase(historyRepo, logger)
	historyService := service.NewHistoryService(historyUseCase)
	grpcServer := server.NewGRPCServer(confServer, historyService, logger)
	httpServer := server.NewHTTPServer(confServer, historyService, logger)
	registrar := data.NewRegistrar(registry)
	app := newApp(logger, grpcServer, httpServer, registrar)
	return app, func() {
		cleanup()
	}, nil
}
