// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"github.com/starryrbs/kfan/app/history/service/internal/biz"
	"github.com/starryrbs/kfan/app/history/service/internal/conf"
	data2 "github.com/starryrbs/kfan/app/history/service/internal/data"
	"github.com/starryrbs/kfan/app/history/service/internal/server"
	"github.com/starryrbs/kfan/app/history/service/internal/service"
)

// Injectors from wire.go:

// initApp init kratos application.
func initApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	asyncProducer := data2.NewKafkaProducer(confData)
	dataData, cleanup, err := data2.NewData(asyncProducer, confData, logger)
	if err != nil {
		return nil, nil, err
	}
	historyRepo := data2.NewHistoryRepo(dataData, logger)
	historyUseCase := biz.NewHistoryUseCase(historyRepo, logger)
	historyService := service.NewHistoryService(historyUseCase)
	grpcServer := server.NewGRPCServer(confServer, historyService, logger)
	app := newApp(logger, grpcServer)
	return app, func() {
		cleanup()
	}, nil
}
