// Code generated by entc, DO NOT EDIT.

package ent

import (
	"github.com/starryrbs/kfan/app/history/service/internal/data/ent/history"
	"github.com/starryrbs/kfan/app/history/service/internal/data/ent/schema"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	historyFields := schema.History{}.Fields()
	_ = historyFields
	// historyDescCreatedAt is the schema descriptor for created_at field.
	historyDescCreatedAt := historyFields[4].Descriptor()
	// history.DefaultCreatedAt holds the default value on creation for the created_at field.
	history.DefaultCreatedAt = historyDescCreatedAt.Default.(func() time.Time)
	// historyDescUpdatedAt is the schema descriptor for updated_at field.
	historyDescUpdatedAt := historyFields[5].Descriptor()
	// history.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	history.DefaultUpdatedAt = historyDescUpdatedAt.Default.(func() time.Time)
}
