// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"log"

	"github.com/starryrbs/kfan/app/house/internal/data/ent/migrate"

	"github.com/starryrbs/kfan/app/house/internal/data/ent/house"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// House is the client for interacting with the House builders.
	House *HouseClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	cfg := config{log: log.Println, hooks: &hooks{}}
	cfg.options(opts...)
	client := &Client{config: cfg}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.House = NewHouseClient(c.config)
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, fmt.Errorf("ent: cannot start a transaction within a transaction")
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:    ctx,
		config: cfg,
		House:  NewHouseClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, fmt.Errorf("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		config: cfg,
		House:  NewHouseClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		House.
//		Query().
//		Count(ctx)
//
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.House.Use(hooks...)
}

// HouseClient is a client for the House schema.
type HouseClient struct {
	config
}

// NewHouseClient returns a client for the House from the given config.
func NewHouseClient(c config) *HouseClient {
	return &HouseClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `house.Hooks(f(g(h())))`.
func (c *HouseClient) Use(hooks ...Hook) {
	c.hooks.House = append(c.hooks.House, hooks...)
}

// Create returns a create builder for House.
func (c *HouseClient) Create() *HouseCreate {
	mutation := newHouseMutation(c.config, OpCreate)
	return &HouseCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of House entities.
func (c *HouseClient) CreateBulk(builders ...*HouseCreate) *HouseCreateBulk {
	return &HouseCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for House.
func (c *HouseClient) Update() *HouseUpdate {
	mutation := newHouseMutation(c.config, OpUpdate)
	return &HouseUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *HouseClient) UpdateOne(h *House) *HouseUpdateOne {
	mutation := newHouseMutation(c.config, OpUpdateOne, withHouse(h))
	return &HouseUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *HouseClient) UpdateOneID(id int64) *HouseUpdateOne {
	mutation := newHouseMutation(c.config, OpUpdateOne, withHouseID(id))
	return &HouseUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for House.
func (c *HouseClient) Delete() *HouseDelete {
	mutation := newHouseMutation(c.config, OpDelete)
	return &HouseDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a delete builder for the given entity.
func (c *HouseClient) DeleteOne(h *House) *HouseDeleteOne {
	return c.DeleteOneID(h.ID)
}

// DeleteOneID returns a delete builder for the given id.
func (c *HouseClient) DeleteOneID(id int64) *HouseDeleteOne {
	builder := c.Delete().Where(house.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &HouseDeleteOne{builder}
}

// Query returns a query builder for House.
func (c *HouseClient) Query() *HouseQuery {
	return &HouseQuery{
		config: c.config,
	}
}

// Get returns a House entity by its id.
func (c *HouseClient) Get(ctx context.Context, id int64) (*House, error) {
	return c.Query().Where(house.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *HouseClient) GetX(ctx context.Context, id int64) *House {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *HouseClient) Hooks() []Hook {
	return c.hooks.House
}
