// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"github.com/starryrbs/kfan/app/house/internal/biz"
	"github.com/starryrbs/kfan/app/house/internal/conf"
	"github.com/starryrbs/kfan/app/house/internal/data"
	"github.com/starryrbs/kfan/app/house/internal/server"
	"github.com/starryrbs/kfan/app/house/internal/service"
)

// Injectors from wire.go:

// initApp init kratos application.
func initApp(confServer *conf.Server, confData *conf.Data, registry *conf.Registry, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	houseRepo := data.NewHouseRepo(dataData, logger)
	houseUseCase := biz.NewHouseUseCase(houseRepo, logger)
	houseService := service.NewHouseService(houseUseCase, logger)
	httpServer := server.NewHTTPServer(confServer, houseService, logger)
	grpcServer := server.NewGRPCServer(confServer, houseService, logger)
	registrar := data.NewRegistrar(registry)
	app := newApp(logger, httpServer, grpcServer, registrar)
	return app, func() {
		cleanup()
	}, nil
}
